language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - EnmShopwareSdkTestCase

before_script:
  - composer self-update
  - composer install

script: php vendor/bin/phpunit --coverage-text

notifications:
  email:
    - bogomolov@eosnewmedia.de
    - marien@eosnewmedia.de